In [15]:
import numpy as np

weight = [73, 67, 98, 54]
height = [1.7, 1.85, 1.9, 1.67]

np_weight = np.array(weight)
np_height = np.array(height)

bmi = np_weight / np_height **2

print(bmi)

light = bmi < 21


print(light)

print(bmi[light])  ## to gówno filtruje arraya 



a = [True, 1, 2 , 3, 4] + [1, 4, 6, 7, False] ## listy zachowują się inaczej niż arraye
print(a)


b = np.array([True, 1, 2 , 3, 4]) + np.array([1, 4, 6, 7, False])  ## arraye zachowują się inaczej niż listy

print(b)

[25.25951557 19.57633309 27.1468144  19.36247266]
[False  True False  True]
[19.57633309 19.36247266]
[True, 1, 2, 3, 4, 1, 4, 6, 7, False]
[ 2  5  8 10  4]


In [3]:
import numpy as np

# arraye w numpy mogą mieć od 1 do 7 wymiarów
# przykład dwuwymiaowej

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball

np_baseball = np.array(baseball)

# Print out the type of np_baseball

print(type(np_baseball))

# Print out the shape of np_baseball

print(np_baseball.shape)


print(baseball)
print(np_baseball)

<class 'numpy.ndarray'>
(4, 2)
[[180, 78.4], [215, 102.7], [210, 98.5], [188, 75.2]]
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


In [ ]:
# wyjmowanie wartości z array

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball

print(np_baseball[49])

# Select the entire second column of np_baseball: np_weight_lb

np_weight_lb = np_baseball[:,1]
np_weight_lb

# Print out height of 124th player

print(np_baseball[123,0])

In [19]:
#korelacja corrcoef

import numpy as np

x = np.array([1 , 2 , 3 , 4 , 5 , 6])
y = np.array([6 , 5 , 4 , 3 , 2 , 1])


np.corrcoef(x,y)


x = np.array([1000 , 200 , 300 , 40 , 50000 , 60])
y = np.array([6000 , 5 , 40 , 3 , 20000 , 1])


np.corrcoef(x,y)



array([[1.        , 0.95941114],
       [0.95941114, 1.        ]])

In [20]:
import numpy as np

# Dane: ilość czasu nauki w godzinach i wyniki egzaminacyjne
czas_nauki = np.array([10, 9, 6, 7, 8, 12, 5, 4, 8, 11])
wyniki_egzaminu = np.array([85, 88, 75, 78, 80, 92, 70, 68, 82, 90])

# Obliczenie macierzy korelacji
macierz_korelacji = np.corrcoef(czas_nauki, wyniki_egzaminu)

# Wyświetlenie wyniku
print("Macierz korelacji:")
print(macierz_korelacji)

# Wypisanie współczynnika korelacji między czasem nauki a wynikami egzaminu
korelacja = macierz_korelacji[0, 1]
print("\nWspółczynnik korelacji między czasem nauki a wynikami egzaminu:", korelacja)

Macierz korelacji:
[[1.         0.97737832]
 [0.97737832 1.        ]]

Współczynnik korelacji między czasem nauki a wynikami egzaminu: 0.9773783247351188


In [27]:
osoby = np.array(['pupi','kacper','kitki'])

numerek = np.array([8 , 13 , 11])

numerek[osoby == 'pupi']



print(osoby[osoby == 'pupi'])

['pupi']
