## display zamiast print

In [4]:
import pandas as pd

df = pd.DataFrame({'Pieski':['Morgan','Basia','Nela','Dexter'], 'Wiek':[8,6,6,5]})

display(df)

print('to so wszystkie pieski')

Pieski  Wiek
0  Morgan     8
1   Basia     6
2    Nela     6
3  Dexter     5

to so wszystkie pieski


## arraye, filtrowanie i operacje na nich

In [2]:
import numpy as np

osoby = np.array(['pupi','kacper','kitki'])

numerek = np.array([8 , 13 , 11])

print(numerek[osoby == 'pupi'])


print(osoby[osoby == 'pupi'])

[8]
['pupi']


In [ ]:
import numpy as np

x = [9,2,3,4] + [5,6,7,8,1]

print(x.index(x.count(x[0])))

In [3]:
import numpy as np

# arraye w numpy mogą mieć od 1 do 7 wymiarów
# przykład dwuwymiaowej

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball

np_baseball = np.array(baseball)

# Print out the type of np_baseball

print(type(np_baseball))

# Print out the shape of np_baseball

print(np_baseball.shape)


print(baseball)
print(np_baseball)

<class 'numpy.ndarray'>
(4, 2)
[[180, 78.4], [215, 102.7], [210, 98.5], [188, 75.2]]
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


In [1]:
# arraye, operacje matematyczne na nich i ich filtrowanie jednym warunkiem

import numpy as np

weight = [73, 67, 98, 54]
height = [1.7, 1.85, 1.9, 1.67]

np_weight = np.array(weight)
np_height = np.array(height)

bmi = np_weight / np_height **2

print(bmi)

light = bmi < 21 # w light tworzy się array wartości true/false


print(light)

print(bmi[light])  ## to gówno filtruje arraya 

print(bmi[bmi < 21])

a = [True, 1, 2 , 3, 4] + [1, 4, 6, 7, False] ## listy zachowują się inaczej niż arraye
print(a)


b = np.array([True, 1, 2 , 3, 4]) + np.array([1, 4, 6, 7, False])  ## arraye zachowują się inaczej niż listy

print(b)

[25.25951557 19.57633309 27.1468144  19.36247266]
[False  True False  True]
[19.57633309 19.36247266]
[19.57633309 19.36247266]
[True, 1, 2, 3, 4, 1, 4, 6, 7, False]
[ 2  5  8 10  4]


In [16]:
# logiczne operatory a NumPy, filtrowanie wieloma warunkami

import numpy as np

weight_ks = [73, 69, 63, 72]
weight_kz = [61, 59, 57, 58]

np_weight_ks = np.array(weight_ks)
np_weight_kz = np.array(weight_kz)

# na jednym arrayu

#logical_and

print(np.logical_and(np_weight_ks > 70, np_weight_ks > 63))

print(np_weight_ks[np.logical_and(np_weight_ks > 70, np_weight_ks > 63)])

#logical_or

print(np.logical_or(np_weight_ks > 70, np_weight_ks > 63))

print(np_weight_ks[np.logical_or(np_weight_ks > 70, np_weight_ks > 63)])

#logical_not 

print(np.logical_not(np_weight_ks > 70, np_weight_ks > 63))

print(np_weight_ks[np.logical_not(np_weight_ks > 70, np_weight_ks > 63)])


# na > 1 arrayu


print(np.logical_and(np_weight_ks > 70, np_weight_kz >= 59))

print(np_weight_ks[np.logical_and(np_weight_ks > 70, np_weight_kz >= 59)])
print(np_weight_kz[np.logical_and(np_weight_ks > 70, np_weight_kz >= 59)])

[ True False False  True]
[73 72]
[ True  True False  True]
[73 69 72]
[False  True  True False]
[69 63]
[ True False False False]
[73]
[61]


In [ ]:
# wyjmowanie wartości z array

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball

print(np_baseball[49])

# Select the entire second column of np_baseball: np_weight_lb

np_weight_lb = np_baseball[:,1]
np_weight_lb

# Print out height of 124th player

print(np_baseball[123,0])

In [ ]:
# dostęp do wartości w np.arrayach -- zarówno w jednowymiarowych, jak i wielowymiarowych [ 1 2 3] jak i [[1 2 3] [4 5 6]

import numpy as np

pojedynczy = np.array([1,2,3,4,5,6,7,8,9])

for liczba in pojedynczy:
    print(f'Liczba jest : {liczba}')

podwojny = np.array([[1,22,333,4444,55555],[9,88,777,6666,55555]])

for liczba in np.nditer(podwojny):
    print(f'W drugim jest liczba: {liczba}')

## korelacja corrcoef

In [19]:
#korelacja corrcoef

import numpy as np

x = np.array([1 , 2 , 3 , 4 , 5 , 6])
y = np.array([6 , 5 , 4 , 3 , 2 , 1])


np.corrcoef(x,y)


x = np.array([1000 , 200 , 300 , 40 , 50000 , 60])
y = np.array([6000 , 5 , 40 , 3 , 20000 , 1])


np.corrcoef(x,y)



array([[1.        , 0.95941114],
       [0.95941114, 1.        ]])

In [20]:
import numpy as np

# Dane: ilość czasu nauki w godzinach i wyniki egzaminacyjne
czas_nauki = np.array([10, 9, 6, 7, 8, 12, 5, 4, 8, 11])
wyniki_egzaminu = np.array([85, 88, 75, 78, 80, 92, 70, 68, 82, 90])

# Obliczenie macierzy korelacji
macierz_korelacji = np.corrcoef(czas_nauki, wyniki_egzaminu)

# Wyświetlenie wyniku
print("Macierz korelacji:")
print(macierz_korelacji)

# Wypisanie współczynnika korelacji między czasem nauki a wynikami egzaminu
korelacja = macierz_korelacji[0, 1]
print("\nWspółczynnik korelacji między czasem nauki a wynikami egzaminu:", korelacja)

Macierz korelacji:
[[1.         0.97737832]
 [0.97737832 1.        ]]

Współczynnik korelacji między czasem nauki a wynikami egzaminu: 0.9773783247351188


## słowniki

In [1]:
# słowniki

# Definition of dictionary
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

#dodaj austrię

europe['austria'] = 'vienna'

# Update capital of germany

europe['germany'] = 'berlin'

# Remove australia

del(europe['australia'])

# Print europe

europe


europe['italy']

'rome'

In [2]:
# słownik słowników

# Dictionary of dictionaries
europe = { 'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } }


# Print out the capital of France

print(europe['france']['capital'])

# Create sub-dictionary data

data = {'capital' : 'rome', 'population' : 59.83}

# Add data to europe under key 'italy'

europe['italy'] = data


# Print europe


print(europe)

paris
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'italy': {'capital': 'rome', 'population': 59.83}}


## pętla po słowniku

In [1]:
# for + enumerate -- dzięki temu ma też dostęp do indeksu danej wartości w liście

# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Change for loop to use enumerate() and update print()
for index, area in enumerate(areas) :
    print(index,area)

0 11.25
1 18.0
2 20.0
3 10.75
4 9.5


In [1]:
# dostęp do kluczy i wartości słownika w pętli for

# Definition of dictionary
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw', 'austria':'vienna' }
          
# Iterate over europe

for key,value in europe.items():
    print(f'{key} -- {value}')

spain -- madrid
france -- paris
germany -- berlin
norway -- oslo
italy -- rome
poland -- warsaw
austria -- vienna


## pętla po liście

In [2]:
# dostęp do list w liście w pętli for

# house list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]
         
# Build a for loop from scratch

for list_ in (house):
    print(f'the {list_[0]} is {list_[1]} sqm')

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm


In [ ]:
#iteracja

## pętelka for:

# Create a list of strings: flash
flash = ['jay garrick', 'barry allen', 'wally west', 'bart allen']

# Print each list item in flash using a for loop
for item in flash:
    print(item)



## ale może zostać zastąpiona iteracją:
### TU JEST ITERACJA
# # Create an iterator for flash: superhero

superhero = iter(flash) # lista jest iterowalna, ale nie można iterować bezpośrednio po niej, trzeba określić ją metodą iter i wrzucić do zmiennej


# Print each item from the iterator
print(next(superhero))
print(next(superhero))
print(next(superhero))
print(next(superhero))


In [ ]:
# enumerate

# Create a list of strings: mutants
mutants = ['charles xavier', 
            'bobby drake', 
            'kurt wagner', 
            'max eisenhardt', 
            'kitty pryde']

# Create a list of tuples: mutant_list
mutant_list = list(enumerate(mutants)) # tworzy listę krotek indeks - wartość 

# Print the list of tuples
print(mutant_list)

# Unpack and print the tuple pairs
for index1,value1 in enumerate(mutants):
    print(index1, value1)

# Change the start index
for index2,value2 in enumerate(mutants,start=1): # można mu określić startowy 'indeks'
    print(index2, value2)


## krotki

In [4]:
#tuple, krotki

#elementów krotki po zdefiniowaniu nie można zmieniać
#elementy krotki można wypakowywać do zmiennych

nums = (1,4,6)

num1,num2,num3 = nums

print(num1)
print(num2)
print(num3)

1
4
6


## zipowanie

In [12]:
# zipowanie

mutants = ['charles xavier', 'bobby drake', 'kurt wagner', 'max eisenhardt', 'kitty pryde']
powers = ['telepathy', 'thermokinesis', 'teleportation', 'magnetokinesis', 'intangibility']


# Create a zip object from mutants and powers: z1
z1 = zip(mutants,powers)


# Print the tuples in z1 by unpacking with *
print(*z1) # wypakowywanie elementów sprawia że z1 się zużywa

# Re-create a zip object from mutants and powers: z1
z1 = zip(mutants,powers) 

# 'Unzip' the tuples in z1 by unpacking with * and zip(): result1, result2
result1, result2 = zip(*z1) # wypakowuję zipa krotek do zmiennych (które stają się krotkami)- 1 element z krotki idzie do result1, drugi do result2

# # Check if unpacked tuples are equivalent to original tuples
print(result1 == mutants) ## pierwotnie elementy były w listach, teraz są w krotkach, dlatego FALSE
print(result2 == powers)  ## pierwotnie elementy były w listach, teraz są w krotkach, dlatego FALSE


print(result1)
print(result2)

('charles xavier', 'telepathy') ('bobby drake', 'thermokinesis') ('kurt wagner', 'teleportation') ('max eisenhardt', 'magnetokinesis') ('kitty pryde', 'intangibility')
False
False
('charles xavier', 'bobby drake', 'kurt wagner', 'max eisenhardt', 'kitty pryde')
('telepathy', 'thermokinesis', 'teleportation', 'magnetokinesis', 'intangibility')


## własna funkcja na liście

In [25]:
superhero_list = ['thor','lala']

def to_upper(heroes):
    for i in heroes:
        yield i.upper()
    




print(list(to_upper(superhero_list)))

['THOR', 'LALA']
